zuul:
  sensitive-headers:
  routes:
    user:
      sensitiveHeaders:
      serviceId: user
#     myProduct:
#       path: /myProduct/**
#       serviceId: product
#       sensitiveHeaders:
    product: /myProduct/**
  ignored-patterns:
spring:
  redis:
    host: 192.168.99.100
    port: 6379
    - /**/product/listForOrder
#    - /product/product/listForOrder
#    - /myProduct/product/listForOrder
